// AUTO-GENERATED from the Zoho sales exports (Apr 2024 – Jun 2026).
// 449 distinct product names taken verbatim from the "Item Name" column.
// Used as the suggestion list for the Warranty Management product field.
// The field is a free-text input backed by these suggestions, so staff can
// also type a product that is not in this list.

export const WARRANTY_PRODUCTS: readonly string[] = [
  "1 TB HDD SATA",
  "11.6\" TOUCH PANEL",
  "12V Adopter",
  "12V Adopter - Touch POS Sytem Adopter",
  "1TB SSD",
  "2\" BT MOBILE PRINTER",
  "2\" Thermal Paper Roll",
  "24V All-in-One Touch POS adapter",
  "24V Thermal Printer Adopter",
  "250*300mm(PANSIZE)HMB Pole GD 30kg-5G",
  "32 Signage Display",
  "43\" Android Smart TV",
  "4GB DDR3 RAM",
  "500 GB HDD SATA",
  "55\" Digital Menu DIsplay",
  "55\" Samsung Signage Display",
  "6U RACK",
  "ACCESSORIES",
  "Acer 20\" LED Monitor",
  "ADAPTER",
  "ADAPTER(8504)",
  "AHUJA 10W Sterio Wall mount Speakers",
  "Ahuja 4 Speakers setup",
  "AHUJA 8W Sterio Ceiling mount Speakers",
  "AHUJA Audio Type DP Mixer Amplifier",
  "Android/Google Smart LED TV - 127cm (50\")",
  "APC PRO 1500UPS APC BACK-UPS PRO BR1500-IN 1500VA/865 WUPS",
  "APC UPS 1.1 KVA",
  "Assembled Desktop Combination - Giga",
  "Assembled Desktop Combination 2",
  "Assembled Desktop Combination 3",
  "ASSEMLED DESKTOP INTEL I3-12TH GENERATION COMBINATION OF GIGA 1",
  "ASSEMPLED DESKTOP PC COMBINATION1",
  "BACK BOX",
  "Beetel Phone",
  "BILL STAR POWER",
  "Billmaxo ARC 1 User",
  "Billmaxo Retail Software (Basic) License",
  "BILLMAXO STANDARD 1 USER LICENSE",
  "Billmaxo Standard 1+ User License",
  "Blue Feather 1TB Hard Disk",
  "Blue Feather 3TB Hard Disk",
  "BLUE FEATHER 4TB HDD",
  "Blue Feather 500gb HDD",
  "BNC CONNECTOR",
  "Bottom Plate for SK-POS Kiosk series S215PA",
  "Cabinet",
  "Cable Manager",
  "CANNON 790 INK BOTTLE BLACK",
  "CANNON INK BOTTLE 790 COLOUR C/Y/M",
  "Cannon Inkjet Printer G2010",
  "Card payment charges",
  "Cash Counting Machine",
  "CAT 6 UTP 24A WG SOLID CABLE",
  "Ceiling Mount Stand 26to43-3ftPLB CE322",
  "Commission Income - Petpooja",
  "Computer USB 2.0 Speaker ST-26 (8518)",
  "Computer(Touch POS) set Rental services",
  "Consistent 4TB CC TV Survilence Hard Disk",
  "CONSISTENT HDD 2TB",
  "Courier Charges",
  "CP PLUS 16 CHANNEL HD DVR",
  "CP PLUS 16 CHANNEL HD NVR",
  "CP Plus 16 Port POE Switch - Gigabyte",
  "CP Plus 32 Chanal HD NVR",
  "Cp Plus 4 Chanal Dvr",
  "CP PLUS 6 Cameras setup",
  "Cp Plus 8 channel Dvr",
  "CP Plus 8 Port POE Switch - Gigabyte",
  "CP PLUS BULLET CAMERA",
  "Cp Plus Bullet Camera 2 mp",
  "CP Plus Dome Camera 2MP",
  "CP Plus HD Bullet IP Camera 2MP",
  "CP Plus HD Dome IP Camera 2MP",
  "CP Plus Wifi Camera",
  "CPU FAN",
  "Crucial RAM DDR4 16GB",
  "Crucial RAM DDR4 4gb",
  "D LINK 16 PORT GIGA",
  "D Link 4 U Rack",
  "D Link 4U Rack",
  "D Link 9U Rack",
  "D Link Back Box",
  "D Link Cable Cat6 Utp 100 Mtrs",
  "D link Cat 6 I/O",
  "D Link Cat-6 Patch Card 1 Mtr",
  "D LINK CCTV CABLE",
  "D Link Dual Face Plate",
  "D Link RJ-45 Connectors",
  "D Link RJ-45 Extenders",
  "D Link RJ-45Connectors",
  "D Link Single Face Plate",
  "D Link Switch 5 Port Gigabyte 100/1000",
  "D-LINK CAT 6 UTP NETWORK CABLE",
  "D-LINK CAT 6UTP CABLE-MTR",
  "D-Link Rj 45 Connector",
  "Dahua Camera",
  "DC CONNECTOR",
  "DDR RAM",
  "DELL DESKTOP",
  "DELL KEYBOARD KB216",
  "Dell KM5221W Keyboard Mouse Combo",
  "Dell Laptop",
  "DELL MONITOR 18.5\" D1918H With HDMI",
  "Dell Monitor 20\"",
  "Dell Monitor 24\" LED",
  "DELL MONITOR 27\"",
  "Dell Mouse Optical Usb MS116",
  "DELL OPTICAL MOUSE MS-116",
  "DELL Wireless Combo Keyboard KM117",
  "DELL Wireless Combo Keyboard KM3322W",
  "Dell Wireless Keyboard & Mouse KM5221W",
  "Dell wireless Mouse WM118",
  "DESKTOP PC",
  "Digital Standee Enclosure",
  "Direct Thermal Label",
  "Dlink 2U Rack",
  "Dlink 4U Rack",
  "Dlink 6U Rack",
  "Dlink 9U Rack",
  "Dlink Back Box",
  "Dlink Cable Cat6 Utp 100 Mtrs",
  "DLINK Cable Cat6 UTP 100 Mtrs",
  "DLINK SWITCH 8 PORT GIG (DGS1008)",
  "DT Labels 60*40*1up/1000pr 1\"Core",
  "DT LABLES",
  "ELECTRONIC WEIGHING MACHINE JEWELLERY",
  "ELECTRONIC WEIGHING MACHINE TABLE TOP",
  "Epson Ink Bottle T00v 198(Black)",
  "Epson Ink Bottle T03y 003 Cyan",
  "Epson Ink Bottle T03y 003 Magenta",
  "Epson Ink Bottle T03y 003 Yellow",
  "Epson Printer L3210",
  "Epson Printer L3250",
  "EPSON PRINTER L5290",
  "EPSON TM-T82X-C31CH26461 USB",
  "EPSON Tm-T82X-C31CH26462 NW LAN Network Printwer",
  "ERD Power Supply",
  "ERD Power Supply 16 Channel",
  "ERD POWER SUPPLY 4ch",
  "ERD Power Supply 8 Channel",
  "ESSL K30 Biometric Device",
  "eSSL MB-160H Spl edition with Wifi",
  "eSSL MB-160H Spl edition with Wifi ..",
  "ESSL MB160 with Battery",
  "ESSL MB160 without Battery",
  "EVM 128GB SSD",
  "EVM 16gb Giga Byte Pen Drive",
  "EVM Hdd 256gb Ssd M.2 Small",
  "Film Label",
  "Foxin cabinet",
  "FOXIN HDD 128GB SSD",
  "FOXIN KEYBOARD MOUSE COMBO (FKM-506 Pro)",
  "Foxin Keyboard Mouse Combo (FKM-506 Pro)",
  "FOXIN MONITOR 17\"",
  "Foxin Monitor 18.5\" HDMI",
  "Foxin Monitor 19\" 1950 HDMI",
  "Foxin Monitor 19.5\" HDMI",
  "Foxin Monitor 24\"",
  "Foxin SMPS",
  "FOXIN SMPS",
  "Foxin speaker Fms 375",
  "FRONTECH KEYBOARD MINI",
  "FSHW1_AT 90 mm Flat Screen Holder Wall Mount",
  "Gigabyte Motherboard H110MH",
  "Gigabyte Motherboard H310-MH",
  "GIGABYTE MOTHERBOARD H610MK",
  "HDMI CABLE",
  "HDMI Cable 3mtr",
  "HIKVISION 16 CHANNEL DVR",
  "HIKVISION 16 CHANNEL NVR",
  "HIKVISION 16 PORT POE SWITCH - GIGA",
  "HIKVISION 2 MP BULLET IP CAMERA",
  "HIKVISION 2 MP DOME IP CAMERA",
  "Hikvision 32 Channel NVR",
  "Hikvision 4 Channel DVR",
  "HIKVISION BULLET CAMERA 2 MP",
  "Hikvision Bullet Camera 5mp",
  "HIKVISION DOOM CAMERA 2MP",
  "Hikvivion 4 Channel DVR",
  "Hot Seal Sealing Machine 12\"",
  "HP LAPTOP",
  "HP LASER PRINTER MFP 1188W",
  "HP PEN DRIVE 16 GB",
  "HP PEN DRIVE 32 GB",
  "Hp Printer 126a",
  "HP PRINTER 126NW",
  "HP Printer Lj1008a",
  "Hp Printer M 126A",
  "HP PRINTER M126A",
  "HP TONER CARTIDGE",
  "HP Toner Cartridge 88A CC388A",
  "HP128A LASER PRINTER, Wireless B/W Office Printer (PRINT+SCAN+COPY)",
  "HTM210",
  "HYNIX 16GB RAM",
  "HYNIX DDR3 4GB DESKTOP RAM",
  "HYNIX RAM DDR3 8GB",
  "HYNIX RAM DDR4 8GB",
  "I O Box",
  "IMPACT BY HONEYWELL IHS520BT WIRELESS 2D BARCODE SCANNER",
  "IMPACT HONEYWELL IHS310X 1D SCANNER",
  "Intel CPU Fan",
  "Intel Processor",
  "Intel Processor I3 6th",
  "Intel Processor i3-8th Generaton",
  "Label 50*25*2up/2500pr chr 1\" core",
  "LABEL PRINTING SCALE Q9",
  "LABELS",
  "LABELS 50X25X2ups/2000Labels",
  "Laptop",
  "LAPTOP BATTERY",
  "LED PANEL TOKEN DISPLAY SYSTEM",
  "LENOVO DESKTOP",
  "Lenovo Laptop Think Book 14",
  "Lenovo Mouse",
  "LENOVO SERVER",
  "Lenovo Tab",
  "Lenovo Tab - 9\"",
  "LENOVO TAB K10",
  "LENOVO TAB K9 - 4GB RAM, 64GB Memory, 9\" Screen Android 13",
  "LENOVO TAB M8 - 4GB RAM, 64GB Memory, 8\" Screen",
  "LENOVO TAB M8 - 4GB RAM, 64GB Memory, 9\" Screen",
  "Lenovo tab M8-8505F ZA5G0113IN(2.0hz Quad Core(MTK)Wi Fi only 3gb/32gb up to 256 GB /8\"HD/500mAh/Android 10)",
  "LENOVO TAB M9 - 4GB RAM, 64GB Memory, 9\" Screen Android 13",
  "LENOVO TAB M9 - 4GB RAM, 64GB Memory, 9\" Screen,",
  "Lenovo Tab Tab M9/4gb/64gb",
  "leoxsys-V4R Android 4GB RAM Mini PC",
  "LG MONITOR 18.5\" HDMI",
  "Logitech Keyboard Wireless Combo MK275",
  "Logitech Mouse Wireless M170 Black",
  "Logitech Wireless Touch Keyboard K400",
  "M95 LVDS Mother Board for SK-POS w/oRAM and SSD",
  "Maintainance Contract",
  "Matrix Vision Pro 4/12 EPABX",
  "Miscellaneous",
  "Monitor",
  "Mother Board for Thermal Printer USB",
  "Mother Board for Thermal Printer USB + LAN",
  "Mouse Pad",
  "MSI Graphics Card",
  "MX50 SMART + COUNTING MACHINE",
  "NETGEAR GS605",
  "NGX Bill Star ECR",
  "NGX BILLING MACHINE - SP92TB",
  "NGX BILLING MACHINE - SP93TB",
  "NGX-NBP32TB",
  "NGX-NBP33TB",
  "NOTE COUNTING MACHINE",
  "NUMERIC 1 KVA UPS",
  "Numeric UPS 600va",
  "ORION ELECTRONIC WEIGHING MACHINE - PLATFORM",
  "Orion Electronic Weighing Machine - Table Top",
  "PATCH CARD",
  "PATCH CARD 1mtr",
  "PCIE: Wi-Fi PCBA for 5300 Series",
  "PCIE: Wi-Fi PCBA for J6412 & I3 1115G4 with Antena",
  "PCIE: Wi-Fi PCBA for N95 / N97 / i3 1215 / i5 1235",
  "Petpooja Payroll income",
  "POSIFLEX - PS6216 - Intel 11th Gen TGL I7 Processor - 16GB DDR4 - 128G SSD - NO OS",
  "POWER CABLE",
  "PRINTER HEAD",
  "Printer USB Cabe",
  "PS9120: OMNI DIRECTIONAL BARCODE SCANNER -NEW 2050301109",
  "PVC RAKE BOX",
  "QUICK HEAL ANTIVIRUS 1 USER",
  "Quick heal Antivirus Server Edition 1 User",
  "QUICK HEAL ESSENTIAL 1 USER",
  "RAM",
  "RAM DDR3 8GB",
  "Refurbished Laptop",
  "Refurbished Lenovo Tiny PC",
  "Repairing Charges",
  "RIBBON LBL",
  "RIBBON LBL 105*300mtrs Awr1\"Core",
  "RUGTEK 2D SCANNER CD3200BT E",
  "RUGTEK USB BARCODE SCANNER",
  "RUGTEK USB BARCODE SCANNER 3200u",
  "Sandisk 256GB Micro Sd Card",
  "SANDISK PEN DRIVE",
  "SEAGATE 1 TB HDD SATA SKYHALK",
  "Seagate Expansion 1 TB 2.5\" USB(Ext)",
  "SEAGATE HDD 1TB Sv35",
  "Seagate HDD 4tb",
  "SEAGATE HDD SATA 500 GB INTERNAL",
  "Secureeye POE Switch 16 PORT",
  "SECUREYE",
  "Secureye 8 Port Switch",
  "Secureye AI FAce 3000 Attendence device",
  "Secureye Biometric Device with Face +Finger",
  "Service Charge",
  "SK-POS - EXTREME SERIES - E1115",
  "SK-POS - EXTREME SERIES - E1115 Intel Core i3-1115G4 Tigerlake , 8GB DDR4 RAM , 128GB M.2 SSD, 15.1\" PCAP Touch Screen",
  "SK-POS - EXTREME SERIES - E1115 Intel Core i5-1115G4 Tigerlake , 8GB DDR4 RAM , 128GB M.2 SSD, 15.1\" PCAP Touch Screen",
  "SK-POS - EXTREME SERIES - E5005, Intel Core i3-5005, 8GB RAM , 128GB M.2 SSD, 15.1\" PCAP Touch Screen",
  "SK-POS - EXTREME SERIES - E5200, Intel Core i5-5200, 8GB RAM , 128GB NVMe SSD, 15.1\" PCAP Touch Screen",
  "SK-POS - EXTREME SERIES - E5300, Intel Core i5-5300 / 5200, 8GB RAM , 128GB NVMe SSD, 15.1\" PCAP Touch Screen, No OS",
  "SK-POS - EXTREME SERIES - E5300, Intel Core i5-5300, 8GB RAM , 128GB NVMe SSD, 15.1\" PCAP Touch Screen",
  "SK-POS - EXTREME SERIES - E5300, Intel Core i5-5300, 8GB RAM , 128GB NVMe SSD, 15.1\" PCAP Touch Screen, No OS",
  "SK-POS - EXTREME SERIES - E5300, Intel Core i5-5300, 8GB RAM , 128GB NVMe SSD, 15.6\" PCAP Touch Screen",
  "SK-POS - KIOSK SERIES - K2104A - Quadcore, 4GB RAM, 32GB Memory, 21.5\" PCAP Touch Screen, Android 11, 3\" Thermal Printer with Auto Cutter, Floor Mount",
  "SK-POS - MIGHTY SERIES - M100, Intel N100 Processor, 8GB RAM, 128GB NVMe SSD, 15.1\" PCAP Touch Screen, No OS",
  "SK-POS - MIGHTY SERIES - M100W, Intel N100 Processor, 8GB RAM, 128GB NVMe SSD, 15.6\" PCAP Touch Screen, No OS",
  "SK-POS - MIGHTY SERIES - M6412, Intel Quadcore J-6412 Elkhart Lake, 8GB RAM, 128GB M.2 SSD, 15.1\" PCAP Touch Screen",
  "SK-POS - MIGHTY SERIES - M6412, Intel Quadcore J-6412 Elkhart Lake, 8GB RAM, 128GB M.2 SSD, 15.1\" PCAP Touch Screen, No OS",
  "SK-POS - MIGHTY SERIES - M6412W, Intel Quadcore J6412, 8GB RAM, 128GB M.2 SSD, 15.6\" PCAP Touch Screen",
  "SK-POS - MIGHTY SERIES - M6412W, Intel Quadcore J6412, 8GB RAM, 128GB M.2 SSD, 15.6\" PCAP Touch Screen, No OS",
  "SK-POS - MIGHTY SERIES - M95, Intel N95 Processor, 8GB RAM, 128GB NVMe SSD, 15.1\" PCAP Touch Screen, No OS",
  "SK-POS - MIGHTY SERIES - M95, INTEL N95 PROCESSOR-MOTHER BOARD",
  "SK-POS 10.1\" Non Touch LCD Monitor",
  "SK-POS 10.1\" Non Touch LCD Monitor NS",
  "SK-POS 11.6\" Non Touch LCD Monitor",
  "SK-POS 15.6\" Non Touch 2nd Monitor",
  "SK-POS 32\" Commercial TV - Amlogic S905W2 - 2GB RAM/16GB Storage",
  "SK-POS 32\" Signage Display",
  "SK-POS 43\" Commercial TV - Amlogic S905W2 - 2GB RAM/16GB Storage",
  "SK-POS 50\" Ultra HD 4K Resolution Commercial TV - Amlogic S905W2 - 2GB RAM/16GB Storage",
  "SK-POS 5500W Hand Held 2D Wireless Scanner - BT+USB",
  "SK-POS ANDROID SERIES - A3568, RK3568 CPU, 4GB RAM, 32GB EMCC, ANDROID 11, 15.6\" PCAP TOUCH SCREEN",
  "SK-POS ANDROID SERIES - A3568, RK3568 CPU, 4GB RAM, 32GB EMCC, ANDROID 11, 15.6\" PCAP TOUCH SCREEN FOR KDS",
  "SK-POS Android Tabs",
  "SK-POS COMPACT SERIES - Android - S116A, RK3566, 4GB RAM, 32GB EMCc,11.6\" PCAP Touch Screen, 3\" Built-in Printer with Auto Cutter, Wifi, Android 11",
  "SK-POS COMPACT SERIES - Android - S116A, RK3566, 4GB RAM, 32GB EMCc,11.6\" PCAP Touch Screen, 3\" Built-in Printer with Auto Cutter, Wifi, BT, Android 11",
  "SK-POS COMPACT SERIES - WINDOWS - N116T, N100 Processor, 8GB RAM, 128GB SSD, 11.6\" PCAP Touch Screen, 3\" Built-in Printer with Auto Cutter",
  "SK-POS COMPACT SERIES - WINDOWS - S116W, J4125 Processor, 4GB RAM, 128GB SSD, 11.6\" PCAP Touch Screen, 3\" Built-in Printer with Auto Cutter",
  "SK-POS COMPACT SERIES - WINDOWS - S116W, J4125 Quad Core Processor, 8GB RAM, 128GB SSD, 11.6\" PCAP Touch Screen, 3\" Built-in Printer with Auto Cutter",
  "SK-POS COMPACT SERIES - WINDOWS - S116WT, J4125 Processor, 4GB RAM, 128GB SSD, 11.6\" PCAP Touch Screen, 3\" Built-in Printer with Auto Cutter",
  "SK-POS DISPLAY SIGNAGE 55\"",
  "SK-POS EXTREME SERIES - E10210 - Intel Core i5-10th Gen, 8GB RAM, 128GB SSD, 15.1\" PCAP Touch Screen with Speakers, No OS",
  "SK-POS EXTREME SERIES - E1115T - Intel Core i3-11th Gen Tigerlake Processor, 8GB DDR4 RAM, 128GB NVMe SSD, 15.1\" PCAP Touch Screen, No OS",
  "SK-POS EXTREME SERIES - E1115W - Intel Core i3-11th Gen Tigerlake Processor, 16GB DDR4 RAM, 128GB NVMe SSD, 15.6\" PCAP Touch Screen, No OS",
  "SK-POS EXTREME SERIES - E1115W - Intel Core i3-11th Gen Tigerlake Processor, 8GB DDR4 RAM, 128GB NVMe SSD, 15.6\" PCAP Touch Screen, No OS",
  "SK-POS EXTREME SERIES - E1235 - Intel Core i3-12th Gen 8GB DDR4 RAM, 128GB NVMe SSD, 15.1\" PCAP Touch Screen, No OS",
  "SK-POS EXTREME SERIES - E1235 - Intel Core i5-12th Gen, 8GB RAM, 128GB SSD, 15.1\" PCAP Touch Screen with Speakers, No OS",
  "SK-POS EXTREME SERIES - E4200W - Intel Core i5 - 4200, 8GB RAM, 128GB SSD, 15.6\" PCAP Touch Screen, No OS",
  "SK-POS Extreme Series - E5300 Touch POS System, Intel Cor i5 Processor, 8GB RAM, 128GB NVMe SSD, 15.1\" PCAP Touch Screen",
  "SK-POS EXTREME SERIES - E5300W - Intel Core i5 - 5300 / 5200, 8GB RAM, 128GB SSD, 15.6\" PCAP Touch Screen, No OS",
  "SK-POS EXTREME SERIES - E5300W - Intel Core i5 - 5300, 8GB RAM, 128GB SSD, 15.6\" PCAP Touch Screen, No OS",
  "SK-POS HANDHELD SERIES - H3162Quad Core Processor, 3GB RAM, 16GB Memory, Built in 2\" Thermal Printer , Android 13, Built in Wifi- Bluetooth, With Built-in Battery",
  "SK-POS HANDHELD SERIES - H8002 - 8\" Touch Screen, Quad Core Processor, 3GB RAM, 16GB Memory, Built in 2\" Thermal Printer , Android 13, Built in Wifi- Bluetooth, With Built-in Battery, Dual Sim",
  "SK-POS HANDHELD SERIES - H8003 - 8\" Touch Screen, Quad Core Processor, 3GB RAM, 16GB Memory, Built in 3\" Thermal Printer , Android 13, Built in Wifi- Bluetooth, With Built-in Battery",
  "SK-POS HANDHELD SERIES - H8003 - 8\" Touch Screen, Quad Core Processor, 3GB RAM, 16GB Memory, Built in 3\" Thermal Printer , Android 13, Built in Wifi- Bluetooth, With Built-in Battery, Dual Sim",
  "SK-POS HANDHELD SERIES - Unisoc CPU, 5.99\" Touch Display, 3GB RAM, 16GB Memory, Built in 2\" Thermal Printer , Android 13, Built in Wifi- Bluetooth, With Built-in Battery",
  "SK-POS HH5500 Hand Held 2D Scanner with USB Int",
  "SK-POS K2153 ANDROID SELF SERVICE KIOSK WITH THERMAL RECEIPT PRINTER",
  "SK-POS KDS Series - 156M, Quadcore, 4GB RAM, 32GB Memory, 15.6\" PCAP Touch Screen, Android 11",
  "SK-POS KIOSK SERIES - PREMIUM SELF SERVICE KIOSK - S215 PA 21.5\" PCAP TOUCH SCREEN, ANDROID 11, 3\" THERMAL PRINTER WITH AUTO CUTTER, QR CODE SCANNER , GRAY COLOUR",
  "SK-POS KIOSK SERIES - SELF SERVICE KIOSK - S215 PA 21.5\" PCAP TOUCH SCREEN, ANDROID 11, 3\" THERMAL PRINTER WITH AUTO CUTTER, QR CODE SCANNER , BLACK COLOUR",
  "SK-POS KIOSK SERIES - SELF SERVICE KIOSK - S215 PA 21.5\" PCAP TOUCH SCREEN, ANDROID 11, 3\" THERMAL PRINTER WITH AUTO CUTTER, QR CODE SCANNER , GRAY COLOUR",
  "SK-POS KIOSK SERIES - SELF SERVICE KIOSK - S215 PA 21.5\" PCAP TOUCH SCREEN, ANDROID 11, 3\" THERMAL PRINTER WITH AUTO CUTTER, QR CODE SCANNER , WHITE COLOUR",
  "SK-POS KIOSK SERIES - SELF SERVICE KIOSK - S215KA - 22\" PCAP TOUCH SCREEN, ANDROID 11, 3\" THERMAL PRINTER WITH AUTO CUTTER , WHITE COLOUR",
  "SK-POS KIOSK SERIES - SELF SERVICE KIOSK - S215W - WINDOWS 21.5\" PCAP TOUCH SCREEN,3\" STOUT-THERMAL PRINTER",
  "SK-POS KIOSK SERIES - SELF SERVICE KIOSK - S215W /ANDROID 21.5\" PCAP TOUCH SCREEN,3\" STOUT-THERMAL PRINTER WITH AUTO CUTTER, WHITE COLOUR",
  "SK-POS KIOSK SERIES - SELF SERVICE KIOSK - S215WA /WINDOWS 21.5\" PCAP TOUCH SCREEN,3\" STOUT-THERMAL PRINTE",
  "SK-POS KIOSK SERIES - SELF SERVICE KIOSK - S215WA 21.5\" PCAP TOUCH SCREEN, ANDROID 11, 3\" STOUT-THERMAL PRINTER WITH AUTO CUTTER, WHITE COLOUR",
  "SK-POS KIOSK SERIES - SELF SERVICE KIOSK - S215WA 21.5\" PCAP TOUCH SCREEN, ANDROID 11, 3\" THERMAL PRINTER WITH AUTO CUTTER, WHITE COLOUR",
  "SK-POS KIOSK SERIES - SELF SERVICE KIOSK - S215WA 21.5\" PCAP TOUCH SCREEN, ANDROID 11, 3\" THERMAL PRINTER WITH AUTO CUTTER, WHITE COLOUR STANDARD",
  "SK-POS KIOSK SERIES - SELF SERVICE KIOSK - S32WB 32\" PCAP TOUCH SCREEN, 3\" THERMAL PRINTER WITH AUTO CUTTER, BLACK COLOUR",
  "SK-POS PREMIUM - P1215 - 15.6\" IPS FHD Display, I3-1215 Fanless CPU,8Gb Ram,256Gb M.2 NVMe",
  "SK-POS PREMIUM - P97S - 15\" IPS FHD Display, N97 Fanless CPU,8Gb Ram,128Gb M.2 NVMe",
  "SK-POS PREMIUM - P97W - 15.6\" IPS FHD Display, N97 Fanless CPU,8Gb RAM,128GB M.2 NVMe",
  "SK-POS PREMIUM - PN97SW - 15.6\" IPS FHD Display, N97 Fanless CPU,8Gb RAM,128GB M.2 NVMe",
  "SK-POS RSK583 CASH DRAWER",
  "SK-POS SELF SERVICE KIOSK - S215K 21.5\" PCAP TOUCH SCREEN, ANDROID 11, 3\" THERMAL PRINTER WITH AUTO CUTTER,BLACK/WHITE",
  "SK-POS Self Service Kiosk - SK215A - Quadcore, 4GB RAM, 32GB eMMC, Android 11, 21.5\" PCAP Touch Screen, 3\" Thermal Printer with Auto Cutter, Black Colour",
  "SK-POS SKC582 CASH DRAWER",
  "SK-POS SS680 / PS9120 2D Omni Directional Barcode Scanner - Tabletop",
  "SK-POS SS680 2D Omni Directional Barcode Scanner - HD",
  "SK-POS SS680 2D Omni Directional Barcode Scanner - Tabletop",
  "SK-POS SS680 2D Omni Directional Tabletop Barcode Scanner",
  "SK-POS XL Series - P215L1235U - Intel Core i5-1235U 12th Gen, 8GB RAM, 256GB M.2 NVMe SSD, 21.5\" IPS FHD PCAP Touch Screen",
  "SK-POS XL Series - X3566, RK-3566 CPU, 4GB RAM, 32GB EMMc, 21.5\" Touch Screen, Built-in-Wifi, Android 11",
  "SK-POS XL Series - X6412, Intel Quad Core J642, 8GB RAM, 128GB NVMe SSD, 21.5\" PCAP Touch Screen, Built-in-Wifi, No OS",
  "SK-POS XL SERIES- P97L - 21.5\" IPS FHD Display, N97 Fanless CPU,8Gb RAM,128GB M.2 NVMe",
  "SK-POS XL SERIES- P97L - 21.5\" IPS FHD Display, N97 Fanless CPU,8Gb RAM,256GB M.2 NVMe",
  "SMPS",
  "SOFTWARE",
  "Software",
  "SOL 802 THERMAL PRINTER",
  "SPARE ADAPTER",
  "Spare Adapter GM60-240250-F (24V /2.5A) Prime/A11 For XP-V320M",
  "SPARE: Cutter for Thermal Printer",
  "Spares",
  "SSD",
  "SSD 128 GB",
  "STOUT by SK-POS Thermal Printer - S250CW USB+LAN 230mm/Sec - Black Colour",
  "STOUT by SK-POS Thermal Printer - S250CW USB+LAN 230mm/Sec - White Colour",
  "STOUT by SK-POS Thermal Printer - S250H USB 230mm/Sec",
  "STOUT by SK-POS Thermal Printer - S250H USB+LAN 230mm/Sec",
  "STOUT by SK-POS Thermal Printer - S250H USB+LAN 250mm/Sec",
  "STOUT by SK-POS Thermal Printer - S250H USB, 250mm/Sec",
  "STOUT by SK-POS Thermal Printer - S300U Serial+USB+Ethernet, 300mm/Sec",
  "STOUT by SK-POS Thermal Printer - SK300U",
  "STOUT by SK-POS Thermal Printer - SK300U Serial+USB+Ethernet, 300mm/Sec",
  "STOUT by SK-POS Thermal Printer S200E USB+LAN 200mm/Sec - Grey Colour",
  "TALLY SINGLE USER LICENSE",
  "TENAX 300N THERMAL PRINTER (260mm/SEC,USB+SERIAL+ETHERNET)",
  "Thermal Paper Roll",
  "Thermal Paper Roll 79x25 Meters -3\"",
  "THERMAL PAPER ROLL BLACK 79MM*57MM",
  "Thermal Paper Roll Black 79MM*58MM",
  "Thermal Paper Roll Black79MM-3\"",
  "THERMAL PAPER ROOL BLACK 79MM*57MM",
  "THERMAL PRINTER AUTO CUTTER",
  "THERMAL PRINTER HEAD",
  "Token Display System",
  "TP LINK 16 PORT SWITCH GIGA",
  "TP LINK 5 PORT SWITCH",
  "Tp Link 5port POE Switch (Gigabyte)",
  "TP LINK 5port Switch (Giga)",
  "TP LINK 8 PORT SWICH 1008",
  "TP LINK Access Point",
  "TP LINK Access Point EAP 115",
  "TP LINK ACCESS POINT EAP 610",
  "Tp Link Access Point EAP225",
  "TP LINK ADAPTER",
  "Tp Link POE Switch",
  "TP Link POE Switch 8 Port Giga 100/1000",
  "TP LINK ROUTER",
  "Tp Link Switch 8 Port Giga",
  "TP LINK Switch 8 Port Giga",
  "TP LINK USB Adapter TLWN 823",
  "TP Link USB to LAN Giga UE306",
  "TP ROLLS 55X15mtrs",
  "TP ROLLS 55X25mtrs",
  "TP-Link AC 600 Wifi Receiver",
  "TP-Link Router Dual WAN ER605",
  "TPLINK ADAPTOR",
  "Transport Charges",
  "Tsc Te 244 Barcode Printer",
  "TSC TE-210 Hybrid,MS_4,60W,EPE,IN BARCODE PRINTER",
  "TSC TE-244 Pro Barcode Printer",
  "TSC TE244,Hybrid,DE,60W,EPS,BIS Barcode Printer",
  "TSC TE310, Hybrid,MS_4,60W,EPE,IN",
  "UPS",
  "USB 2.0 SPEAKERS ST-111",
  "VIDEO BALLOON",
  "Viewsonic 22\" PCAP Touch Monitor",
  "Wall Mounting Kit",
  "WI-FI PCBA WITH ANTENA FOR J6412,I3-1115",
  "WI-FI PCBA WITH ANTENA FOR SK-POS",
  "Win 10 IoT Ent 2019 LTSC MultiLang ESD OEI Entry",
  "Windows 10 Pro Operating System",
  "WINDOWS 10 SOFTWARE",
  "Windows 11 Pro Operating System",
  "Windows 11 Pro Operating System Licence",
  "Wooden Packaging",
  "XIAOMI SMART TV 55\"",
  "Zebion monitor 18.5\" led",
  "Zebronics Hdd 128gb Ssd",
];

// Standard warranty durations (months) offered in the dropdown. The form
// also accepts a custom value, so this is a suggestion list too.
export const WARRANTY_DURATIONS_MONTHS: readonly number[] = [6, 12, 18, 24, 36];
